# Generated by Django 4.2.13 on 2024-10-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantsDetail',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('plant_name', models.CharField(max_length=100)),
            ],
        ),
    ]
