# Generated by Django 4.2.13 on 2024-10-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUsers',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('user_password', models.CharField(max_length=20)),
                ('user_email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'userData',
            },
        ),
    ]
