# Generated by Django 4.2.13 on 2024-07-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('First', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'MyBooks',
            },
        ),
    ]
